# Teacher information - Join
    - Author: Santiago Avella. Git hub: https://github.com/TiagoMimi

In [204]:
import pandas as pd
from pathlib import Path
import warnings
warnings.filterwarnings("ignore")
# *Configure pandas to display all columns in DataFrame outputs*
pd.set_option('display.max_columns', None)

## Load the data

In [205]:
# Current working directory
script_path = Path.cwd()

# Find the project folder
project_path = script_path

while project_path.name != "saber11_db":
    project_path = project_path.parent

### 2024

In [206]:
# The folder containing the TXT files
data_path = project_path / "data" / "source" / "teacher" / "2024"

# List of TXT files
file_list = [
    data_path / "Docentes escalafonados según estatuto docente.csv",
    data_path / "Docentes ocupados en CLEI (con mayor asignación académica).csv",
    data_path / "Docentes ocupados en la sede educativa según escalafón y tipo de vinculación laboral.csv",
    data_path / "Docentes ocupados según carácter por nivel educativo (educación tradicional) con mayor asignación académica.csv",
    data_path / "Docentes por jornada según máximo nivel educativo alcanzado y rangos de edad.csv"
]

# Choose the DataFrame name for each file
df_names = [
    "df_escalafon",
    "df_clei",
    "df_vinculacion",
    "df_nivel_educativo",
    "df_jornada_edad"
]

# Read each CSV separately
dataframes = {}

for name, file in zip(df_names, file_list):
    dataframes[name] = pd.read_csv(file, sep=",")

df_escalafon_2024 = dataframes["df_escalafon"]
df_clei_2024 = dataframes["df_clei"]
df_vinculacion_2024 = dataframes["df_vinculacion"]
df_nivel_educativo_2024 = dataframes["df_nivel_educativo"]
df_jornada_edad_2024 = dataframes["df_jornada_edad"]

### 2023

In [207]:
# The folder containing the TXT files
data_path = project_path / "data" / "source" / "teacher" / "2023"

# List of TXT files
file_list = [
    data_path / "Docentes escalafonados según estatuto docente.csv",
    data_path / "Docentes ocupados en CLEI (con mayor asignación académica).csv",
    data_path / "Docentes ocupados en la sede educativa según escalafón y tipo de vinculación laboral.csv",
    data_path / "Docentes ocupados según carácter por nivel educativo (educación tradicional) con mayor asignación académica.csv",
    data_path / "Docentes por jornada según máximo nivel educativo alcanzado y rangos de edad.csv"
]

# Choose the DataFrame name for each file
df_names = [
    "df_escalafon",
    "df_clei",
    "df_vinculacion",
    "df_nivel_educativo",
    "df_jornada_edad"
]

# Read each CSV separately
dataframes = {}

for name, file in zip(df_names, file_list):
    dataframes[name] = pd.read_csv(file, 
                                sep=",",
                                encoding="latin-1")

df_escalafon_2023 = dataframes["df_escalafon"]
df_clei_2023 = dataframes["df_clei"]
df_vinculacion_2023 = dataframes["df_vinculacion"]
df_nivel_educativo_2023 = dataframes["df_nivel_educativo"]
df_jornada_edad_2023 = dataframes["df_jornada_edad"]

### 2022

In [208]:
# The folder containing the TXT files
data_path = project_path / "data" / "source" / "teacher" / "2022"

# List of TXT files
file_list = [
    data_path / "Docentes escalafonados según estatuto docente.csv",
    data_path / "Docentes ocupados en CLEI (con mayor asignación académica).csv",
    data_path / "Docentes ocupados en la sede educativa según escalafón y tipo de vinculación laboral.csv",
    data_path / "Docentes ocupados según carácter por nivel educativo (educación tradicional) con mayor asignación académica.csv",
    data_path / "Docentes por jornada según máximo nivel educativo alcanzado y rangos de edad.csv"
]

# Choose the DataFrame name for each file
df_names = [
    "df_escalafon",
    "df_clei",
    "df_vinculacion",
    "df_nivel_educativo",
    "df_jornada_edad"
]

# Read each CSV separately
dataframes = {}

for name, file in zip(df_names, file_list):
    dataframes[name] = pd.read_csv(file, 
                                sep=",",
                                encoding="latin-1")

df_escalafon_2022 = dataframes["df_escalafon"]
df_clei_2022 = dataframes["df_clei"]
df_vinculacion_2022 = dataframes["df_vinculacion"]
df_nivel_educativo_2022 = dataframes["df_nivel_educativo"]
df_jornada_edad_2022 = dataframes["df_jornada_edad"]

### 2021

In [209]:
# The folder containing the TXT files
data_path = project_path / "data" / "source" / "teacher" / "2021"

# List of TXT files
file_list = [
    data_path / "Docentes escalafonados según estatuto docente.csv",
    data_path / "Docentes ocupados en CLEI (mayor asignación académica).csv",
    data_path / "Docentes ocupados en la sede educativa según escalafón y tipo de vinculación laboral.csv",
    data_path / "Docentes ocupados según carácter por nivel educativo (educación tradicional) con mayor asignación académica.csv",
    data_path / "Máximo nivel educativo alcanzado por los docente según rangos de edad por jornada.csv",
    data_path / "Máximo nivel educativo alcanzado por los docentes según rangos de edad por nivel educativo.csv"
]

# Choose the DataFrame name for each file
df_names = [
    "df_escalafon",
    "df_clei",
    "df_vinculacion",
    "df_asignacion_academica",
    "df_nivel_educativo",
    "df_jornada_edad"
]

# Read each CSV separately
dataframes = {}

for name, file in zip(df_names, file_list):
    dataframes[name] = pd.read_csv(file, 
                                sep=",",
                                encoding="latin-1")

df_escalafon_2021 = dataframes["df_escalafon"]
df_clei_2021 = dataframes["df_clei"]
df_vinculacion_2021 = dataframes["df_vinculacion"]
df_nivel_educativo_2021 = dataframes["df_nivel_educativo"]
df_asignacion_academica_2021 = dataframes["df_asignacion_academica"]
df_jornada_edad_2021 = dataframes["df_jornada_edad"]

### 2020

In [210]:
# The folder containing the TXT files
data_path = project_path / "data" / "source" / "teacher" / "2020"

# List of TXT files
file_list = [
    data_path / "Docentes escalafonados según estatuto docente.csv",
    data_path / "Docentes ocupados en CLEI (mayor asignación académica).csv",
    data_path / "Docentes ocupados en la sede educativa según escalafón y tipo de vinculación laboral.csv",
    data_path / "Docentes ocupados según carácter por nivel educativo (educación tradicional) con mayor asignación académica.csv",
    data_path / "Máximo nivel educativo alcanzado por los docente según rangos de edad por jornada.csv",
    data_path / "Máximo nivel educativo alcanzado por los docentes según rangos de edad por nivel educativo.csv"
]

# Choose the DataFrame name for each file
df_names = [
    "df_escalafon",
    "df_clei",
    "df_vinculacion",
    "df_asignacion_academica",
    "df_nivel_educativo",
    "df_jornada_edad"
]
# Read each CSV separately
dataframes = {}

for name, file in zip(df_names, file_list):
    dataframes[name] = pd.read_csv(file, 
                                sep=";")

df_escalafon_2020 = dataframes["df_escalafon"]
df_clei_2020 = dataframes["df_clei"]
df_vinculacion_2020 = dataframes["df_vinculacion"]
df_nivel_educativo_2020 = dataframes["df_nivel_educativo"]
df_asignacion_academica_2020 = dataframes["df_asignacion_academica"]
df_jornada_edad_2020 = dataframes["df_jornada_edad"]

### 2019

In [211]:
# The folder containing the TXT files
data_path = project_path / "data" / "source" / "teacher" / "2019"

# List of TXT files
file_list = [
    data_path / "Docentes escalafonados según estatuto docente.csv",
    data_path / "Docentes ocupados en CLEI (mayor asignación académica).csv",
    data_path / "Docentes ocupados en la sede educativa según escalafón y tipo de vinculación laboral.csv",
    data_path / "Docentes ocupados según carácter por nivel educativo (educación tradicional) con mayor asignación académica.csv",
    data_path / "Máximo nivel educativo alcanzado por los docente según rangos de edad por jornada.csv",
    data_path / "Máximo nivel educativo alcanzado por los docentes según rangos de edad por nivel educativo.csv"
]

# Choose the DataFrame name for each file
df_names = [
    "df_escalafon",
    "df_clei",
    "df_vinculacion",
    "df_asignacion_academica",
    "df_nivel_educativo",
    "df_jornada_edad"
]
# Read each CSV separately
dataframes = {}

for name, file in zip(df_names, file_list):
    dataframes[name] = pd.read_csv(file, 
                                sep=";")

df_escalafon_2019 = dataframes["df_escalafon"]
df_clei_2019 = dataframes["df_clei"]
df_vinculacion_2019 = dataframes["df_vinculacion"]
df_nivel_educativo_2019 = dataframes["df_nivel_educativo"]
df_asignacion_academica_2019 = dataframes["df_asignacion_academica"]
df_jornada_edad_2019 = dataframes["df_jornada_edad"]

### 2018

In [212]:
# The folder containing the TXT files
data_path = project_path / "data" / "source" / "teacher" / "2018"

# List of TXT files
file_list = [
    data_path / "Docentes escalafonados según estatuto docente.csv",
    data_path / "Docentes ocupados en CLEI (mayor asignación académica).csv",
    data_path / "Docentes ocupados en la sede educativa según escalafón y tipo de vinculación laboral.csv",
    data_path / "Docentes ocupados según carácter por nivel educativo (educación tradicional) con mayor asignación académica.csv",
    data_path / "Máximo nivel educativo alcanzado por los docente según rangos de edad por jornada.csv",
    data_path / "Máximo nivel educativo alcanzado por los docentes según rangos de edad por nivel educativo.csv"
]

# Choose the DataFrame name for each file
df_names = [
    "df_escalafon",
    "df_clei",
    "df_vinculacion",
    "df_asignacion_academica",
    "df_nivel_educativo",
    "df_jornada_edad"
]

# Read each CSV separately
dataframes = {}

for name, file in zip(df_names, file_list):
    dataframes[name] = pd.read_csv(file, 
                                sep=",",
                                encoding="latin-1")

df_escalafon_2018 = dataframes["df_escalafon"]
df_clei_2018 = dataframes["df_clei"]
df_vinculacion_2018 = dataframes["df_vinculacion"]
df_nivel_educativo_2018 = dataframes["df_nivel_educativo"]
df_asignacion_academica_2018 = dataframes["df_asignacion_academica"]
df_jornada_edad_2018 = dataframes["df_jornada_edad"]

### 2017

In [213]:
# The folder containing the TXT files
data_path = project_path / "data" / "source" / "teacher" / "2017"

# List of TXT files
file_list = [
    data_path / "Docentes escalafonados según estatuto docente.csv",
    data_path / "Docentes ocupados en CLEI (mayor asignación académica).csv",
    data_path / "Docentes ocupados en la sede educativa según escalafón y tipo de vinculación laboral.csv",
    data_path / "Docentes ocupados según carácter por nivel educativo (educación tradicional) con mayor asignación académica.csv",
    data_path / "Último nivel educativo alcanzado por los docentes según rangos de edad por nivel educativo.txt",
    data_path / "Último nivel educativo alcanzado por los docente según rangos de edad por jornada.csv"
]

# Choose the DataFrame name for each file
df_names = [
    "df_escalafon",
    "df_clei",
    "df_vinculacion",
    "df_asignacion_academica",
    "df_nivel_educativo",
    "df_jornada_edad"
]

# Read each CSV separately
dataframes = {}

for name, file in zip(df_names, file_list):
    dataframes[name] = pd.read_csv(file, 
                                sep=";",
                                encoding="latin-1")

df_escalafon_2017 = dataframes["df_escalafon"]
df_clei_2017 = dataframes["df_clei"]
df_vinculacion_2017 = dataframes["df_vinculacion"]
df_asignacion_academica_2017 = dataframes["df_asignacion_academica"]
df_jornada_edad_2017 = dataframes["df_jornada_edad"]

In [214]:
data_path = project_path / "data" / "source" / "teacher" / "2017"

file_list = [
    data_path / "Último nivel educativo alcanzado por los docentes según rangos de edad por nivel educativo.txt"]

df_names = [
    "df_nivel_educativo"]

for name, file in zip(df_names, file_list):    
    dataframes[name] = pd.read_csv(file, 
                                sep="\t",
                                encoding="latin-1")
                                
df_nivel_educativo_2017 = dataframes["df_nivel_educativo"]

In [215]:
df_escalafon_2017 = df_escalafon_2017.rename(columns={"ï»¿SEDE_CODIGO":"SEDE_CODIGO"})
df_clei_2017 = df_clei_2017.rename(columns={"ï»¿SEDE_CODIGO":"SEDE_CODIGO"})
df_vinculacion_2017 = df_vinculacion_2017.rename(columns={"ï»¿SEDE_CODIGO":"SEDE_CODIGO"})
df_asignacion_academica_2017 = df_asignacion_academica_2017.rename(columns={"ï»¿SEDE_CODIGO":"SEDE_CODIGO"})
df_jornada_edad_2017 = df_jornada_edad_2017.rename(columns={"ï»¿SEDE_CODIGO":"SEDE_CODIGO"})

### 2016

In [216]:
# The folder containing the TXT files
data_path = project_path / "data" / "source" / "teacher" / "2016"

# List of TXT files
file_list = [
    data_path / "Docentes escalafonados según estatuto docente.txt",
    data_path / "Docentes ocupados en CLEI (mayor asignación académica).txt",
    data_path / "Docentes ocupados en la sede educativa según escalafón y tipo de vinculación laboral.txt",
    data_path / "Docentes ocupados, según carácter, por nivel educativo (educación tradicional) donde tiene la mayor asignación académica.txt",
    data_path / "Último nivel educativo alcanzado por el docente,  nivel educativo donde tiene la mayor asignación académica y rango de edad del docente por jornada.txt",
    data_path / "Último nivel educativo alcanzado por los docentes  con asignación académica y edad del docente.txt"]

# Choose the DataFrame name for each file
df_names = [
    "df_escalafon",
    "df_clei",
    "df_vinculacion",
    "df_asignacion_academica",
    "df_nivel_educativo",
    "df_jornada_edad"
]

# Read each TXT separately
dataframes = {}

for name, file in zip(df_names, file_list):
    dataframes[name] = pd.read_csv(
        file,
        sep="\t",
        encoding="latin-1"
    )

# Assign DataFrames
df_escalafon_2016 = dataframes["df_escalafon"]
df_clei_2016 = dataframes["df_clei"]
df_vinculacion_2016 = dataframes["df_vinculacion"]
df_asignacion_academica_2016 = dataframes["df_asignacion_academica"]
df_nivel_educativo_2016 = dataframes["df_nivel_educativo"]
df_jornada_edad_2016 = dataframes["df_jornada_edad"]

### 2015

In [217]:
# The folder containing the TXT files
data_path = project_path / "data" / "source" / "teacher" / "2015"

# List of TXT files
file_list = [
    data_path / "Docentes escalafonados según estatuto docente.csv",
    data_path / "Docentes ocupados según cáracter, para niveles de enseñanza CLEI y Otros Modelos.csv",
    data_path / "Docentes ocupados en la sede educativa.csv",
    data_path / "Docentes ocupados según cáracter,para los niveles de enseñanza prees, pri,seca y med.csv",
    data_path / "útimo nivel educativo alcanzado por el docente.csv",
    data_path / "Informacion general de docentes por jornada.csv"
]

# Choose the DataFrame name for each file
df_names = [
    "df_escalafon",
    "df_clei",
    "df_vinculacion",
    "df_asignacion_academica",
    "df_nivel_educativo",
    "df_jornada_edad"
]

# Read each CSV separately
dataframes = {}

for name, file in zip(df_names, file_list):
    dataframes[name] = pd.read_csv(file, 
                                sep=",",
                                encoding="latin-1")

df_escalafon_2015 = dataframes["df_escalafon"]
df_clei_2015 = dataframes["df_clei"]
df_vinculacion_2015 = dataframes["df_vinculacion"]
df_nivel_educativo_2015 = dataframes["df_nivel_educativo"]
df_asignacion_academica_2015 = dataframes["df_asignacion_academica"]
df_jornada_edad_2015 = dataframes["df_jornada_edad"]

## Concat

#### Escalafon

In [218]:
df_escalafon = pd.concat([df_escalafon_2015,
                        df_escalafon_2016,
                        df_escalafon_2017,
                        df_escalafon_2018,
                        df_escalafon_2019,
                        df_escalafon_2020,
                        df_escalafon_2021,
                        df_escalafon_2022,
                        df_escalafon_2023,
                        df_escalafon_2024], axis=0)

In [219]:
df_escalafon

,SEDE_CODIGO,PERIODO_ID,PERIODO_ANIO,GRADOESCA_ID,GRADOESCA_CODIGO,GRADOESCA_NOMBRE,SEDEDOES_CANTIDAD_HOMBRE,SEDEDOES_CANTIDAD_MUJER
0,308758001975,2,2015,9,7,Grado 7,2,3
1,308758076142,2,2015,15,13,Grado 13,0,1
2,283094000442,2,2015,14,12,Grado 12,0,1
3,315238001464,2,2015,22,2A_SE,Grado 2A Sin especialización,0,1
4,308758001975,2,2015,6,4,Grado 4,0,2
...,...,...,...,...,...,...,...,...
133491,325269004131,11,2024,9,7,Grado 7,0,4
133492,273686000211,11,2024,16,14,Grado 14,0,1
133493,227615061063,11,2024,22,2A_SE,Grado 2A Sin especialización,0,1
133494,252250000242,11,2024,16,14,Grado 14,0,1
133495,252250000242,11,2024,22,2A_SE,Grado 2A Sin especialización,0,1

#### Clei

In [220]:
df_clei = pd.concat([df_clei_2015,
                        df_clei_2016,
                        df_clei_2017,
                        df_clei_2018,
                        df_clei_2019,
                        df_clei_2020,
                        df_clei_2021,
                        df_clei_2022,
                        df_clei_2023,
                        df_clei_2024], axis=0)

In [221]:
df_clei

,SEDE_CODIGO,PERIODO_ID,PERIODO_ANIO,NIVELENSE_ID,NIVELENSE_CODIGO,NIVELENSE_NOMBRE,SEDEDONI_CANTIDAD_HOMBRE,SEDEDONI_CANTIDAD_MUJER
0,341298000034,2,2015,5,5,CLEI (Ciclos lectivos integrados - decreto 301...,6,2
1,386568061022,2,2015,5,5,CLEI (Ciclos lectivos integrados - decreto 301...,8,3
2,168547000551,2,2015,6,6,Otros modelos educativos para jóvenes y adultos,0,2
3,311001109389,2,2015,5,5,CLEI (Ciclos lectivos integrados - decreto 301...,9,3
4,308001001676,2,2015,5,5,CLEI (Ciclos lectivos integrados - decreto 301...,1,2
...,...,...,...,...,...,...,...,...
2013,444001003793,11,2024,5,5,CLEI (Ciclos lectivos integrados - decreto 301...,0,2
2014,350001007093,11,2024,5,5,CLEI (Ciclos lectivos integrados - decreto 301...,3,4
2015,311001108684,11,2024,5,5,CLEI (Ciclos lectivos integrados - decreto 301...,13,10
2016,141001005203,11,2024,5,5,CLEI (Ciclos lectivos integrados - decreto 301...,0,3
2017,325307800001,11,2024,5,5,CLEI (Ciclos lectivos integrados - decreto 301...,0,3

#### Vinculacion

In [222]:
df_vinculacion = pd.concat([df_vinculacion_2015,
                        df_vinculacion_2016,
                        df_vinculacion_2017,
                        df_vinculacion_2018,
                        df_vinculacion_2019,
                        df_vinculacion_2020,
                        df_vinculacion_2021,
                        df_vinculacion_2022,
                        df_vinculacion_2023,
                        df_vinculacion_2024], axis=0)

In [223]:
df_vinculacion

,SEDE_CODIGO,PERIODO_ID,PERIODO_ANIO,VINCULA_ID,VINCULA_CODIGO,VINCULA_NOMBRE,SEDEDOC_CANTIDAD_HOMBRE,SEDEDOC_CANTIDAD_MUJER
0,285001001340,2,2015,1,1,"Docentes de planta, con grado en el escalafón",7,7
1,285001001340,2,2015,2,2,"Docentes por contrato, con grado en el escalafón",0,2
2,250223000203,2,2015,1,1,"Docentes de planta, con grado en el escalafón",1,1
3,268101000781,2,2015,1,1,"Docentes de planta, con grado en el escalafón",5,4
4,268101000781,2,2015,2,2,"Docentes por contrato, con grado en el escalafón",1,1
...,...,...,...,...,...,...,...,...
62278,244560000975,11,2024,3,3,"Docentes de planta, sin grado en el escalafón",11,28
62279,244560000975,11,2024,1,1,"Docentes de planta, con grado en el escalafón",0,1
62280,413140000259,11,2024,1,1,"Docentes de planta, con grado en el escalafón",4,2
62281,413140000259,11,2024,2,2,Docentes contrato o canasta educativa (con gra...,3,2
62282,254001003196,11,2024,1,1,"Docentes de planta, con grado en el escalafón",15,18

#### Asignacion academica

In [224]:
df_asignacion_academica = pd.concat([df_asignacion_academica_2015,
                        df_asignacion_academica_2016,
                        df_asignacion_academica_2017,
                        df_asignacion_academica_2018,
                        df_asignacion_academica_2019,
                        df_asignacion_academica_2020,
                        df_asignacion_academica_2021,
                        df_nivel_educativo_2022,
                        df_nivel_educativo_2023,
                        df_nivel_educativo_2024], axis=0)

In [225]:
df_asignacion_academica

,SEDE_CODIGO,PERIODO_ID,PERIODO_ANIO,CARACTER_ID,CARACTER_CODIGO,CARACTER_NOMBRE,NIVELENSE_ID,NIVELENSE_CODIGO,NIVELENSE_NOMBRE,ESPECIALIDAD_ID,ESPECIALIDAD_CODIGO,ESPECIALIDAD_NOMBRE,SEDEDOCA_CANTIDAD_HOMBRE,SEDEDOCA_CANTIDAD_MUJER
0,250287000223,2,2015,1,1,Académico,2,2,Básica primaria,16,10,Todas las áreas,0,1
1,244001002747,2,2015,1,1,Académico,1,1,Preescolar,16,10,Todas las áreas,0,1
2,244001002747,2,2015,1,1,Académico,2,2,Básica primaria,16,10,Todas las áreas,0,1
3,244560003362,2,2015,1,1,Académico,1,1,Preescolar,16,10,Todas las áreas,1,3
4,244560003362,2,2015,1,1,Académico,2,2,Básica primaria,16,10,Todas las áreas,6,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260769,368547001998,11,2024,1,1,Académico,2,2,Básica primaria,1,3,Ciencias naturales y educación ambiental,1,1
260770,368547001998,11,2024,1,1,Académico,2,2,Básica primaria,2,4,"Ciencias sociales, historia, geografía, consti...",0,1
260771,368547001998,11,2024,1,1,Académico,2,2,Básica primaria,5,7,"Humanidades, lengua castellana",0,2
260772,368547001998,11,2024,1,1,Académico,2,2,Básica primaria,7,9,Matemáticas,0,2
260773,368547001998,11,2024,1,1,Académico,1,1,Preescolar,18,1,Dimensiones,0,3

#### Nivel educativo

In [226]:
# Columns to keep in the age-related DataFrames
age_columns = [
    "SEDE_CODIGO",
    "PERIODO_ID",
    "PERIODO_ANIO",
    "NIVELEDUCDOC_ID",
    "NIVELEDUCDOC_CODIGO",
    "NIVELEDUCDOC_NOMBRE"
]

# Store the original DataFrames by year
age_dataframes = {
    2016: df_jornada_edad_2016,
    2017: df_jornada_edad_2017,
    2018: df_jornada_edad_2018,
    2019: df_jornada_edad_2019,
    2020: df_jornada_edad_2020,
    2021: df_jornada_edad_2021,
    2022: df_jornada_edad_2022,
    2023: df_jornada_edad_2023,
    2024: df_jornada_edad_2024
}

# Keep only the required columns for each year
age_dataframes = {
    year: df[age_columns].copy()
    for year, df in age_dataframes.items()
}

# Create individual DataFrames
df_educacion_2016 = age_dataframes[2016]
df_educacion_2017 = age_dataframes[2017]
df_educacion_2018 = age_dataframes[2018]
df_educacion_2019 = age_dataframes[2019]
df_educacion_2020 = age_dataframes[2020]
df_educacion_2021 = age_dataframes[2021]
df_educacion_2022 = age_dataframes[2022]
df_educacion_2023 = age_dataframes[2023]
df_educacion_2024 = age_dataframes[2024]

In [227]:
df_educacion = pd.concat([df_educacion_2016,
                    df_educacion_2017,
                    df_educacion_2018,
                    df_educacion_2019,
                    df_educacion_2020,
                    df_educacion_2021,
                    df_educacion_2022,
                    df_educacion_2023,
                    df_educacion_2024], axis=0)

In [ ]:
df_educacion

,SEDE_CODIGO,PERIODO_ID,PERIODO_ANIO,NIVELEDUCDOC_ID,NIVELEDUCDOC_CODIGO,NIVELEDUCDOC_NOMBRE
0,205483000236,3,2016,3,3,Normalista superior
1,205483000236,3,2016,3,3,Normalista superior
2,205483000236,3,2016,6,6,Tecnólogo en educación
3,205483000236,3,2016,7,7,Licenciado
4,205483000236,3,2016,7,7,Licenciado
...,...,...,...,...,...,...
274602,205120001095,11,2024,7,7,Licenciado
274603,205120001095,11,2024,9,9,Posgrado en educación o programa pedagógico
274604,205120001095,11,2024,9,9,Posgrado en educación o programa pedagógico
274605,205120001095,11,2024,9,9,Posgrado en educación o programa pedagógico
274606,205120001095,11,2024,9,9,Posgrado en educación o programa pedagógico

#### Edad

In [195]:
# Columns to keep in the age-related DataFrames
age_columns = [
    "SEDE_CODIGO",
    "PERIODO_ID",
    "PERIODO_ANIO",
    "RANGODOCENTE_ID",
    "RANDOC_NOMBRE"
]

# Store the original DataFrames by year
age_dataframes = {
    2016: df_jornada_edad_2016,
    2017: df_jornada_edad_2017,
    2018: df_jornada_edad_2018,
    2019: df_jornada_edad_2019,
    2020: df_jornada_edad_2020,
    2021: df_jornada_edad_2021,
    2022: df_jornada_edad_2022,
    2023: df_jornada_edad_2023,
    2024: df_jornada_edad_2024
}

# Keep only the required columns for each year
age_dataframes = {
    year: df[age_columns].copy()
    for year, df in age_dataframes.items()
}

# Create individual DataFrames
df_edad_2016 = age_dataframes[2016]
df_edad_2017 = age_dataframes[2017]
df_edad_2018 = age_dataframes[2018]
df_edad_2019 = age_dataframes[2019]
df_edad_2020 = age_dataframes[2020]
df_edad_2021 = age_dataframes[2021]
df_edad_2022 = age_dataframes[2022]
df_edad_2023 = age_dataframes[2023]
df_edad_2024 = age_dataframes[2024]

In [196]:
df_edad = pd.concat([df_edad_2016,
                    df_edad_2017,
                    df_edad_2018,
                    df_edad_2019,
                    df_edad_2020,
                    df_edad_2021,
                    df_edad_2022,
                    df_edad_2023,
                    df_edad_2024], axis=0)

In [197]:
df_edad

,SEDE_CODIGO,PERIODO_ID,PERIODO_ANIO,RANGODOCENTE_ID,RANDOC_NOMBRE
0,205483000236,3,2016,3,Entre 26 y 30 años
1,205483000236,3,2016,5,Entre 36 y 40 años
2,205483000236,3,2016,6,Mayor a 40 años
3,205483000236,3,2016,5,Entre 36 y 40 años
4,205483000236,3,2016,5,Entre 36 y 40 años
...,...,...,...,...,...
274602,205120001095,11,2024,11,Mayor a 56 aÃ±os
274603,205120001095,11,2024,10,Entre 51 y 55 aÃ±os
274604,205120001095,11,2024,9,Entre 46 y 50 aÃ±os
274605,205120001095,11,2024,11,Mayor a 56 aÃ±os
274606,205120001095,11,2024,11,Mayor a 56 aÃ±os

#### Jornada

In [200]:
# Columns to keep in the age-related DataFrames
age_columns = [
    "SEDE_CODIGO",
    "PERIODO_ID",
    "PERIODO_ANIO",
    "JORNADA_ID",
    "JORNADA_CODIGO",
    "JORNADA_NOMBRE",
    "JORDOC_CANTIDAD_HOMBRE",
    "JORDOC_CANTIDAD_MUJER"
]

# Store the original DataFrames by year
age_dataframes = {
    2016: df_jornada_edad_2016,
    2017: df_jornada_edad_2017,
    2018: df_jornada_edad_2018,
    2019: df_jornada_edad_2019,
    2020: df_jornada_edad_2020,
    2021: df_jornada_edad_2021,
    2022: df_jornada_edad_2022,
    2023: df_jornada_edad_2023,
    2024: df_jornada_edad_2024
}

# Keep the required columns and ignore missing columns
age_dataframes = {
    year: df.reindex(columns=age_columns).copy()
    for year, df in age_dataframes.items()
}

# Create individual DataFrames
df_jornada_2016 = age_dataframes[2016]
df_jornada_2017 = age_dataframes[2017]
df_jornada_2018 = age_dataframes[2018]
df_jornada_2019 = age_dataframes[2019]
df_jornada_2020 = age_dataframes[2020]
df_jornada_2021 = age_dataframes[2021]
df_jornada_2022 = age_dataframes[2022]
df_jornada_2023 = age_dataframes[2023]
df_jornada_2024 = age_dataframes[2024]

In [202]:
df_jornada = pd.concat([df_jornada_2016,
                    df_jornada_2017,
                    df_jornada_2018,
                    df_jornada_2019,
                    df_jornada_2020,
                    df_jornada_2021,
                    df_jornada_2022,
                    df_jornada_2023,
                    df_jornada_2024], axis=0)
df_jornada

,SEDE_CODIGO,PERIODO_ID,PERIODO_ANIO,JORNADA_ID,JORNADA_CODIGO,JORNADA_NOMBRE,JORDOC_CANTIDAD_HOMBRE,JORDOC_CANTIDAD_MUJER
0,205483000236,3,2016,NaN,NaN,NaN,NaN,NaN
1,205483000236,3,2016,NaN,NaN,NaN,NaN,NaN
2,205483000236,3,2016,NaN,NaN,NaN,NaN,NaN
3,205483000236,3,2016,NaN,NaN,NaN,NaN,NaN
4,205483000236,3,2016,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
274602,205120001095,11,2024,2.0,2.0,Mañana,2.0,0.0
274603,205120001095,11,2024,2.0,2.0,Mañana,0.0,1.0
274604,205120001095,11,2024,2.0,2.0,Mañana,0.0,1.0
274605,205120001095,11,2024,2.0,2.0,Mañana,0.0,1.0
274606,205120001095,11,2024,2.0,2.0,Mañana,1.0,0.0

## Write csv

In [229]:
# Output folder for joined CSV files
joined_path = project_path / "data" / "joined"

# Create folder if it does not exist
joined_path.mkdir(parents=True, exist_ok=True)

In [232]:
dataframes = {
    "teacher_rank": df_escalafon,
    "teacher_clei": df_clei,
    "teacher_employment": df_vinculacion,
    "teacher_academic_assignment": df_asignacion_academica,
    "teacher_education": df_educacion,
    "teacher_age": df_edad,
    "teacher_schedule": df_jornada
}

for name, df in dataframes.items():
    df.to_csv(
        joined_path / f"{name}.csv",
        sep=";",
        index=False,
        encoding="utf-8-sig"
    )