# Saber 11 test - Join
    - Author: Santiago Avella. Git hub: https://github.com/TiagoMimi

In [24]:
import pandas as pd
from pathlib import Path
import warnings
warnings.filterwarnings("ignore")
# *Configure pandas to display all columns in DataFrame outputs*
pd.set_option('display.max_columns', None)

## Load data

In [25]:
# Current working directory
script_path = Path.cwd()

# Find the project folder
project_path = script_path

while project_path.name != "saber11_db":
    project_path = project_path.parent

# The folder containing the TXT files
data_path = project_path / "data" / "source" / "saber11_results"

In [26]:
# List of TXT files
file_list = [
    data_path / "Examen_Saber_11_20151.txt",
    data_path / "Examen_Saber_11_20152.txt",
    data_path / "Examen_Saber_11_20161.txt",
    data_path / "Examen_Saber_11_20162.txt",
    data_path / "Examen_Saber_11_20171.txt",
    data_path / "Examen_Saber_11_20172.txt",
    data_path / "Examen_Saber_11_20181.txt",
    data_path / "Examen_Saber_11_20182.txt",
    data_path / "Examen_Saber_11_20191.txt",
    data_path / "Examen_Saber_11_20192.txt",
    data_path / "Examen_Saber_11_20201.txt",
    data_path / "Examen_Saber_11_20202.txt",
    data_path / "Examen_Saber_11_20211.txt",
    data_path / "Examen_Saber_11_20212.txt",
    data_path / "Examen_Saber_11_20221.txt",
    data_path / "Examen_Saber_11_20222.txt",
    data_path / "Examen_Saber_11_20231.txt",
    data_path / "Examen_Saber_11_20232.txt",
    data_path / "Examen_Saber_11_20241.txt",
    data_path / "Examen_Saber_11_20242.txt"
]

# Read all TXT files
dataframes = [
    pd.read_csv(file, sep=";")
    for file in file_list
]

# Concatenate all files
df_saber11 = pd.concat(
    dataframes,
    axis=0,
    ignore_index=True
)

In [27]:
df_saber11["cole_cod_dane_establecimiento"] = df_saber11["cole_cod_dane_establecimiento"].astype("str")
df_saber11["cole_cod_dane_sede"] = df_saber11["cole_cod_dane_sede"].astype("str")
df_saber11["cole_cod_depto_ubicacion"] = df_saber11["cole_cod_depto_ubicacion"].astype("str")
df_saber11["cole_cod_mcpio_ubicacion"] = df_saber11["cole_cod_mcpio_ubicacion"].astype("str")
df_saber11["cole_codigo_icfes"] = df_saber11["cole_codigo_icfes"].astype("str")
df_saber11["estu_cod_depto_presentacion"] = df_saber11["estu_cod_depto_presentacion"].astype("str")
df_saber11["estu_cod_mcpio_presentacion"] = df_saber11["estu_cod_mcpio_presentacion"].astype("str")
df_saber11["estu_cod_reside_depto"] = df_saber11["estu_cod_reside_depto"].astype("str")
df_saber11["estu_cod_reside_mcpio"] = df_saber11["estu_cod_reside_mcpio"].astype("str")

#### remove the .0 on the rows

In [28]:
columns = [
    "cole_cod_dane_establecimiento",
    "cole_cod_dane_sede",
    "cole_cod_depto_ubicacion",
    "cole_cod_mcpio_ubicacion",
    "cole_codigo_icfes",
    "estu_cod_depto_presentacion",
    "estu_cod_mcpio_presentacion",
    "estu_cod_reside_depto",
    "estu_cod_reside_mcpio"
]

for col in columns:
    df_saber11[col] = (
        df_saber11[col]
        .astype(str)
        .str.replace(r"\.0$", "", regex=True)
    )

In [29]:
df_saber11

,periodo,estu_consecutivo,estu_estudiante,estu_tipodocumento,cole_area_ubicacion,cole_bilingue,cole_calendario,cole_caracter,cole_cod_dane_establecimiento,cole_cod_dane_sede,cole_cod_depto_ubicacion,cole_cod_mcpio_ubicacion,cole_codigo_icfes,cole_depto_ubicacion,cole_genero,cole_jornada,cole_mcpio_ubicacion,cole_naturaleza,cole_nombre_establecimiento,cole_nombre_sede,cole_sede_principal,desemp_ingles,estu_agregado,estu_cod_depto_presentacion,estu_cod_mcpio_presentacion,estu_cod_reside_depto,estu_cod_reside_mcpio,estu_depto_presentacion,estu_depto_reside,estu_etnia,estu_fechanacimiento,estu_genero,estu_grado,estu_inse_individual,estu_mcpio_presentacion,estu_mcpio_reside,estu_nacionalidad,estu_nse_individual,estu_pais_reside,estu_pilopaga,estu_privado_libertad,fami_cuartoshogar,fami_educacionmadre,fami_educacionpadre,fami_estratovivienda,fami_numlibros,fami_personashogar,fami_tieneautomovil,fami_tienecomputador,fami_tieneinternet,fami_tienelavadora,fami_tieneserviciotv,punt_c_naturales,punt_global,punt_ingles,punt_lectura_critica,punt_matematicas,punt_sociales_ciudadanas,estu_tieneetnia,desemp_c_naturales,desemp_lectura_critica,desemp_matematicas,desemp_sociales_ciudadanas,estu_discapacidad,estu_nse_establecimiento,estu_repite,percentil_c_naturales,percentil_global,percentil_ingles,percentil_lectura_critica,percentil_matematicas,percentil_sociales_ciudadanas,fami_numhermanos,estu_dedicacioninternet,estu_dedicacionlecturadiaria,estu_horassemanatrabaja,estu_tiporemuneracion,fami_comecarnepescadohuevo,fami_comecerealfrutoslegumbre,fami_comelechederivados,fami_situacioneconomica,fami_tieneconsolavideojuegos,fami_tienehornomicroogas,fami_tienemotocicleta,fami_trabajolabormadre,fami_trabajolaborpadre,estu_generacione,estu_grupoetnia
0,20151,SB11201510000485,ESTUDIANTE,CC,URBANO,S,B,ACADÉMICO,311769000921,311769000921,11,11001,19406,BOGOTA,MIXTO,COMPLETA,BOGOTÁ D.C.,NO OFICIAL,COL HELVETIA,COL HELVETIA,S,B+,S,11,11001,11,11001,BOGOTA,BOGOTA,Ninguno,25/09/1995,M,11.0,74.361115,BOGOTÁ D.C.,BOGOTÁ D.C.,COLOMBIA,NSE4,COLOMBIA,NO,N,Tres,Educación profesional completa,Educación profesional completa,Estrato 6,MÁS DE 100 LIBROS,Cuatro,Si,Si,Si,Si,Si,69,347,90.0,64,72,66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20151,SB11201510115564,ESTUDIANTE,TI,URBANO,N,A,NaN,376250000871,376250000871,76,76250,170563,VALLE,MIXTO,SABATINA,EL DOVIO,NO OFICIAL,CENTRO DOCENTE PARA ADULTOS - EDIMA,CENTRO DOCENTE PARA ADULTOS - EDIMA - SEDE PRI...,S,A-,S,76,76622,76,76250,VALLE,VALLE,Ninguno,19/06/1998,F,26.0,44.367836,ROLDANILLO,EL DOVIO,COLOMBIA,NSE2,COLOMBIA,NO,N,Tres,Secundaria (Bachillerato) incompleta,Secundaria (Bachillerato) completa,Estrato 1,0 A 10 LIBROS,Cinco,No,No,No,No,No,48,239,45.0,49,48,47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20151,SB11201510097089,ESTUDIANTE,TI,URBANO,N,A,ACADÉMICO,311001105928,311001105928,11,11001,112300,BOGOTA,MIXTO,MAÑANA,BOGOTÁ D.C.,NO OFICIAL,CENT EDUC PROEDUCAR,CENT EDUC PROEDUCAR,S,A-,S,11,11001,11,11001,BOGOTA,BOGOTA,Ninguno,09/12/1997,M,26.0,52.914814,BOGOTÁ D.C.,BOGOTÁ D.C.,COLOMBIA,NSE3,COLOMBIA,NO,N,Siete,Primaria completa,Secundaria (Bachillerato) incompleta,Estrato 2,0 A 10 LIBROS,Once,No,Si,Si,Si,Si,34,166,41.0,18,43,35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20151,SB11201510115560,ESTUDIANTE,CC,URBANO,N,A,NaN,376250000871,376250000871,76,76250,170563,VALLE,MIXTO,SABATINA,EL DOVIO,NO OFICIAL,CENTRO DOCENTE PARA ADULTOS - EDIMA,CENTRO DOCENTE PARA ADULTOS - EDIMA - SEDE PRI...,S,A-,S,76,76622,76,76622,VALLE,VALLE,Ninguno,10/02/1997,F,26.0,43.844238,ROLDANILLO,ROLDANILLO,COLOMBIA,NSE2,COLOMBIA,NO,N,Dos,Primaria completa,Primaria incompleta,Estrato 1,11 A 25 LIBROS,Tres,No,No,No,Si,Si,34,183,42.0,51,29,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20151,SB11201510002784,ESTUDIANTE,TI,URBANO,S,B,ACADÉMICO,308001004209,308001004209,8,8001,3459,ATLANTICO,MIXTO,COMPLETA,BARRANQUILLA,NO OFICIAL,COLEGIO MARYMOUNT,COLEGIO MARYMOUNT - SEDE PRINCIPAL,S,B+,S,8,8001,8,8001,ATLANTICO,ATLANTICO,Sikuani,13/01/1997,M,11.0,86.204170,BARRANQUILLA,BARRANQUILLA,COLOMBIA,NSE4,COLOMBIA,NO,N,Cuatro,Postgrado,Postgrado,Estrato 6,26 A 100 LIBROS,Cuatro,Si,Si,Si,Si,Si,69,351,85.0,61,82,64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6665241,20242,SB11202430000016,INDIVIDUAL,CC,NaN,NaN,NaN,NaN,nan,nan,nan,nan,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A1,N,11,11001,11,11001,BOGOTÁ,BOGOTÁ,NaN,05/08/1977,M,NaN,NaN,BOGOTÁ D.C.,BOGOTÁ D.C.,COLOMBIA,NaN,COLOMBIA,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42,228,49.0,49,53,37,NaN,2.0,2.0,3.0,1.0,N,NaN,0.0,25.0,31.0,46.0,31.0,50.0,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NINGUNO
6665242,20242,SB11202430041817,INDIVIDUAL,TI,NaN,NaN,NaN,NaN,nan,nan,nan,nan,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A-,N,85,85410,85,85410,CASANARE,CASANARE,NaN,16/10/2006,F,NaN,NaN,TAURAMENA,TAURAMENA,COLOMBIA,NaN,COLOMBIA,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,54,257,46.0,51,49,53,NaN,2.0,3.0,2.0,2.0,N,NaN,0.0,64.0,51.0,35.0,38.0,39.0,63.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NINGUNO
6665243,20242,SB11202430073368,INDIVIDUAL,CC,NaN,NaN,NaN,NaN,nan,nan,nan,nan,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A-,N,5,5615,5,5615,ANTIOQUIA,ANTIOQUIA,NaN,17/09/1987,F,NaN,NaN,RIONEGRO,RIONEGRO,COLOMBIA,NaN,COLOMBIA,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41,195,44.0,40,29,44,NaN,2.0,2.0,1.0,2.0,N,NaN,0.0,22.0,12.0,28.0,11.0,4.0,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NINGUNO
6665244,20242,SB11202430051722,INDIVIDUAL,CC,NaN,NaN,NaN,NaN,nan,nan,nan,nan,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A1,N,17,17380,17,17380,CALDAS,CALDAS,NaN,17/08/2005,M,NaN,NaN,LA DORADA,LA DORADA,COLOMBIA,NaN,COLOMBIA,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,69,348,57.0,73,68,73,NaN,3.0,4.0,3.0,4.0,N,NaN,0.0,96.0,96.0,69.0,98.0,90.0,98.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NINGUNO
6665245,20242,SB11202430274808,INDIVIDUAL,CC,NaN,NaN,NaN,NaN,nan,nan,nan,nan,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A1,N,11,11001,11,11001,BOGOTÁ,BOGOTÁ,NaN,16/04/2004,F,NaN,NaN,BOGOTÁ D.C.,BOGOTÁ D.C.,COLOMBIA,NaN,COLOMBIA,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47,248,48.0,47,53,52,NaN,2.0,2.0,3.0,2.0,N,NaN,0.0,41.0,45.0,42.0,26.0,52.0,59.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NINGUNO

## Quality of the data

In [30]:
def dataframe_quality_function(dataframe):

    try:
        column_summary = []
        for col in dataframe.columns:                                      # *Iterate through the dataset columns*
            total_rows = len(dataframe)                                    # *Calculate the total number of rows*
            n_nulls = dataframe[col].isna().sum()                         # *Calculate the number of null values per column*
            percent_null = ((n_nulls / total_rows) * 100).round(2)        # *Calculate the percentage of null values*
            non_null = total_rows - n_nulls                               # *Calculate the number of non-null values*
            percent_non_null = ((non_null / total_rows) * 100).round(2)   # *Calculate the percentage of non-null values*
            dtype = dataframe[col].dtype                                   # *Get the data type of the column*
            column_summary.append({                                       # *Create the data quality summary for reporting or export*

                "Column_Name": col,
                "Data_Type": dtype,
                "Valid_Records": non_null,
                "Percentage_Valid_Records": percent_non_null,
                "Null_Records": n_nulls,
                "Percentage_Null_Records": percent_null
            })

        df_quality_summary = pd.DataFrame(column_summary)
        df_quality_summary.to_excel("saber11_dataframe_quality.xlsx")
        print("Excel completed")

        return df_quality_summary
    except Exception as e:
        print("Excel creation was not completed")

In [31]:
dataframe_quality_function(df_saber11)

Excel completed

,Column_Name,Data_Type,Valid_Records,Percentage_Valid_Records,Null_Records,Percentage_Null_Records
0,periodo,int64,6665246,100.00,0,0.00
1,estu_consecutivo,object,6665246,100.00,0,0.00
2,estu_estudiante,object,6665246,100.00,0,0.00
3,estu_tipodocumento,object,6665234,100.00,12,0.00
4,cole_area_ubicacion,object,5681663,85.24,983583,14.76
...,...,...,...,...,...,...
83,fami_tienemotocicleta,object,4341643,65.14,2323603,34.86
84,fami_trabajolabormadre,object,4339409,65.11,2325837,34.89
85,fami_trabajolaborpadre,object,4331876,64.99,2333370,35.01
86,estu_generacione,object,2497270,37.47,4167976,62.53
87,estu_grupoetnia,object,1273578,19.11,5391668,80.89

## Clean the data

### only students

- In the estu_estudiante column, there are two types of records: Estudiante and Individual. This indicates whether the student was registered through a school (the first category) or registered individually (the second category).
- Since our study focuses on schools as educational institutions and aims to examine the relationship between teacher characteristics and student outcomes, we will use only the records categorized as Estudiante.

In [32]:
df_saber11 = df_saber11[df_saber11["estu_estudiante"] == "ESTUDIANTE"]

### Data Organization

We will organize the information into three main categories:

- **Student Information:** Variables describing the student's personal, academic, and demographic characteristics.

- **School Information:** Variables related to the educational institution, such as school characteristics and location.

- **Socioeconomic Information:** Variables describing the student's family background, socioeconomic conditions, and household characteristics.

- **Student Results:** Variables related to the student's academic performance and results obtained in the Saber 11 examination.

#### student_info

In [33]:
df_student_info = df_saber11[["estu_consecutivo",
                            "estu_agregado",
                            "cole_cod_dane_establecimiento",
                            "cole_cod_dane_sede",
                            "estu_dedicacioninternet",
                            "estu_dedicacionlecturadiaria",
                            "estu_depto_reside",
                            "estu_discapacidad",
                            "estu_estudiante",
                            "estu_etnia",
                            "estu_fechanacimiento",
                            "estu_generacione",
                            "estu_genero",
                            "estu_grado",
                            "estu_grupoetnia",
                            "estu_horassemanatrabaja",
                            "estu_nacionalidad",
                            "estu_pilopaga",
                            "estu_privado_libertad",
                            "estu_repite",
                            "estu_tieneetnia",
                            "estu_tipodocumento",
                            "estu_tiporemuneracion",
                            "estu_cod_reside_depto",
                            "estu_cod_reside_mcpio",
                            "estu_mcpio_reside",
                            "estu_pais_reside"
]]

In [34]:
df_student_info = df_student_info.rename(columns={"estu_consecutivo":"student_id",
                                                "cole_cod_dane_establecimiento":"school_institution_id",
                                                "cole_cod_dane_sede":"school_campus_id"})

In [35]:
df_student_info

,student_id,estu_agregado,school_institution_id,school_campus_id,estu_dedicacioninternet,estu_dedicacionlecturadiaria,estu_depto_reside,estu_discapacidad,estu_estudiante,estu_etnia,estu_fechanacimiento,estu_generacione,estu_genero,estu_grado,estu_grupoetnia,estu_horassemanatrabaja,estu_nacionalidad,estu_pilopaga,estu_privado_libertad,estu_repite,estu_tieneetnia,estu_tipodocumento,estu_tiporemuneracion,estu_cod_reside_depto,estu_cod_reside_mcpio,estu_mcpio_reside,estu_pais_reside
0,SB11201510000485,S,311769000921,311769000921,NaN,NaN,BOGOTA,NaN,ESTUDIANTE,Ninguno,25/09/1995,NaN,M,11.0,NaN,NaN,COLOMBIA,NO,N,NaN,NaN,CC,NaN,11,11001,BOGOTÁ D.C.,COLOMBIA
1,SB11201510115564,S,376250000871,376250000871,NaN,NaN,VALLE,NaN,ESTUDIANTE,Ninguno,19/06/1998,NaN,F,26.0,NaN,NaN,COLOMBIA,NO,N,NaN,NaN,TI,NaN,76,76250,EL DOVIO,COLOMBIA
2,SB11201510097089,S,311001105928,311001105928,NaN,NaN,BOGOTA,NaN,ESTUDIANTE,Ninguno,09/12/1997,NaN,M,26.0,NaN,NaN,COLOMBIA,NO,N,NaN,NaN,TI,NaN,11,11001,BOGOTÁ D.C.,COLOMBIA
3,SB11201510115560,S,376250000871,376250000871,NaN,NaN,VALLE,NaN,ESTUDIANTE,Ninguno,10/02/1997,NaN,F,26.0,NaN,NaN,COLOMBIA,NO,N,NaN,NaN,CC,NaN,76,76622,ROLDANILLO,COLOMBIA
4,SB11201510002784,S,308001004209,308001004209,NaN,NaN,ATLANTICO,NaN,ESTUDIANTE,Sikuani,13/01/1997,NaN,M,11.0,NaN,NaN,COLOMBIA,NO,N,NaN,NaN,TI,NaN,8,8001,BARRANQUILLA,COLOMBIA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6630103,SB11202430031940,S,111001012963,111001012963,Entre 1 y 3 horas,30 minutos o menos,BOGOTÁ,N,ESTUDIANTE,NaN,09/04/2007,NaN,F,11.0,NINGUNO,Menos de 10 horas,COLOMBIA,NaN,N,0.0,NaN,TI,"Si, en efectivo",11,11001,BOGOTÁ D.C.,COLOMBIA
6630104,SB11202430002696,S,320001006881,320001006881,Entre 1 y 3 horas,No leo por entretenimiento,CESAR,N,ESTUDIANTE,NaN,06/02/2007,NaN,M,11.0,NINGUNO,NaN,COLOMBIA,NaN,N,0.0,NaN,TI,NaN,20,20001,VALLEDUPAR,COLOMBIA
6630105,SB11202430070974,S,176520002520,176520800222,Entre 1 y 3 horas,30 minutos o menos,VALLE,N,ESTUDIANTE,NaN,24/09/2006,NaN,F,11.0,NINGUNO,0,COLOMBIA,NaN,N,0.0,NaN,TI,No,76,76520,PALMIRA,COLOMBIA
6630106,SB11202430586516,S,305001020558,305001020558,Más de 3 horas,No leo por entretenimiento,ANTIOQUIA,N,ESTUDIANTE,NaN,08/12/2006,NaN,F,26.0,NINGUNO,0,COLOMBIA,NaN,N,0.0,NaN,TI,No,5,5001,MEDELLÍN,COLOMBIA
6630107,SB11202430450964,S,141001001593,141001001593,Entre 30 y 60 minutos,No leo por entretenimiento,HUILA,N,ESTUDIANTE,NaN,25/08/2007,NaN,F,11.0,NINGUNO,0,COLOMBIA,NaN,N,0.0,NaN,TI,No,41,41001,NEIVA,COLOMBIA

#### school_info

In [36]:
df_school_info = (
    df_saber11[
        [
            "cole_area_ubicacion",
            "cole_bilingue",
            "cole_calendario",
            "cole_caracter",
            "cole_cod_dane_establecimiento",
            "cole_cod_dane_sede",
            "cole_cod_depto_ubicacion",
            "cole_cod_mcpio_ubicacion",
            "cole_codigo_icfes",
            "cole_depto_ubicacion",
            "cole_genero",
            "cole_jornada",
            "cole_mcpio_ubicacion",
            "cole_naturaleza",
            "cole_nombre_establecimiento",
            "cole_nombre_sede",
            "cole_sede_principal"
        ]
    ]
    .groupby("cole_cod_dane_sede", as_index=False)
    .agg(lambda x: x.mode().iloc[0] if not x.mode().empty else None)
)

In [37]:
df_school_info = df_school_info.rename(columns={"estu_consecutivo":"student_id",
                                                "cole_cod_dane_establecimiento":"school_institution_id",
                                                "cole_cod_dane_sede":"school_campus_id"})

In [38]:
df_school_info

,school_campus_id,cole_area_ubicacion,cole_bilingue,cole_calendario,cole_caracter,school_institution_id,cole_cod_depto_ubicacion,cole_cod_mcpio_ubicacion,cole_codigo_icfes,cole_depto_ubicacion,cole_genero,cole_jornada,cole_mcpio_ubicacion,cole_naturaleza,cole_nombre_establecimiento,cole_nombre_sede,cole_sede_principal
0,1,URBANO,None,OTRO,ACADÉMICO,1,11,11001,722157,BOGOTÁ,MIXTO,MAÑANA,BOGOTÁ D.C.,OFICIAL,NORMAL SUPERIOR MARIA AUXILIADORA,INSTITUTO COLOMBIANO PARA LA EVALUACIÓN DE LA ...,S
1,105001000001,URBANO,N,A,ACADÉMICO,105001000001,5,5001,113381,ANTIOQUIA,MIXTO,TARDE,MEDELLÍN,OFICIAL,INSTITUCION EDUCATIVA FE Y ALEGRIA JOSE MARIA ...,INST EDUC FE Y ALEGRIA JOSE MARIA VELAZ,S
2,105001000043,URBANO,N,A,ACADÉMICO,105001000043,5,5001,159251,ANTIOQUIA,MIXTO,NOCHE,MEDELLÍN,OFICIAL,INSTITUCION EDUCATIVA BARRIO SANTA CRUZ,INST EDUC BARRIO SANTA CRUZ,S
3,105001000108,URBANO,N,A,TÉCNICO/ACADÉMICO,105001000108,5,5001,724211,ANTIOQUIA,FEMENINO,UNICA,MEDELLÍN,OFICIAL,INSTITUCION EDUCATIVA CENTRO FORMATIVO DE ANTI...,INST EDUC CEFA,S
4,105001000132,URBANO,None,A,ACADÉMICO,105001000132,5,5001,133272,ANTIOQUIA,MIXTO,MAÑANA,MEDELLÍN,OFICIAL,INST EDUC JOSE MARIA BERNAL,INST EDUC JOSE MARIA BERNAL,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13806,847001000027,URBANO,N,A,ACADÉMICO,347001052748,47,47001,152868,MAGDALENA,MIXTO,MAÑANA,SANTA MARTA,NO OFICIAL,CIUDADELA EDUCATIV COOEDUMAG,CIUDADELA EDUCATIV COOEDUMAG,S
13807,847001000035,URBANO,None,A,ACADÉMICO,147001052600,47,47001,135442,MAGDALENA,MIXTO,NOCHE,SANTA MARTA,OFICIAL,INSTITUCION EDUCATIVA DISTRITAL NUEVO AMANECER...,INSTITUCION EDUCATIVA DISTRITAL NUEVO AMANECER...,S
13808,847001000051,URBANO,None,A,NO APLICA,347001053078,47,47001,648279,MAGDALENA,MIXTO,MAÑANA,SANTA MARTA,NO OFICIAL,GIMNASIO BILINGUE DE EDUCACION ACTIVA,GIMNASIO BILINGUE DE EDUCACION ACTIVA,S
13809,854874000001,URBANO,None,A,ACADÉMICO,454001011902,54,54001,168179,NORTE SANTANDER,MIXTO,MAÑANA,CÚCUTA,NO OFICIAL,FUNDACIÓN PARA LA ACTUALIZACIÓN DE LA EDUCACIÓ...,FUNDACION PARA LA ACTUALIZACIÓN DE LA EDUCACIÓ...,S
13810,nan,None,None,None,None,nan,nan,nan,nan,None,None,COMPLETA,None,None,None,None,None

#### result_info

In [39]:
df_result_info = df_saber11[["estu_consecutivo",
                            "cole_cod_dane_establecimiento",
                            "cole_cod_dane_sede",
                            "desemp_c_naturales",
                            "desemp_ingles",
                            "desemp_lectura_critica",
                            "desemp_matematicas",
                            "desemp_sociales_ciudadanas",
                            "estu_cod_depto_presentacion",
                            "estu_cod_mcpio_presentacion",
                            "estu_depto_presentacion",
                            "estu_mcpio_presentacion",
                            "percentil_c_naturales",
                            "percentil_global",
                            "percentil_ingles",
                            "percentil_lectura_critica",
                            "percentil_matematicas",
                            "percentil_sociales_ciudadanas",
                            "periodo",
                            "punt_c_naturales",
                            "punt_global",
                            "punt_ingles",
                            "punt_lectura_critica",
                            "punt_matematicas",
                            "punt_sociales_ciudadanas"
]]

In [40]:
df_result_info = df_result_info.rename(columns={"estu_consecutivo":"student_id",
                                                "cole_cod_dane_establecimiento":"school_institution_id",
                                                "cole_cod_dane_sede":"school_campus_id"})

In [41]:
df_result_info

,student_id,school_institution_id,school_campus_id,desemp_c_naturales,desemp_ingles,desemp_lectura_critica,desemp_matematicas,desemp_sociales_ciudadanas,estu_cod_depto_presentacion,estu_cod_mcpio_presentacion,estu_depto_presentacion,estu_mcpio_presentacion,percentil_c_naturales,percentil_global,percentil_ingles,percentil_lectura_critica,percentil_matematicas,percentil_sociales_ciudadanas,periodo,punt_c_naturales,punt_global,punt_ingles,punt_lectura_critica,punt_matematicas,punt_sociales_ciudadanas
0,SB11201510000485,311769000921,311769000921,NaN,B+,NaN,NaN,NaN,11,11001,BOGOTA,BOGOTÁ D.C.,NaN,NaN,NaN,NaN,NaN,NaN,20151,69,347,90.0,64,72,66
1,SB11201510115564,376250000871,376250000871,NaN,A-,NaN,NaN,NaN,76,76622,VALLE,ROLDANILLO,NaN,NaN,NaN,NaN,NaN,NaN,20151,48,239,45.0,49,48,47
2,SB11201510097089,311001105928,311001105928,NaN,A-,NaN,NaN,NaN,11,11001,BOGOTA,BOGOTÁ D.C.,NaN,NaN,NaN,NaN,NaN,NaN,20151,34,166,41.0,18,43,35
3,SB11201510115560,376250000871,376250000871,NaN,A-,NaN,NaN,NaN,76,76622,VALLE,ROLDANILLO,NaN,NaN,NaN,NaN,NaN,NaN,20151,34,183,42.0,51,29,31
4,SB11201510002784,308001004209,308001004209,NaN,B+,NaN,NaN,NaN,8,8001,ATLANTICO,BARRANQUILLA,NaN,NaN,NaN,NaN,NaN,NaN,20151,69,351,85.0,61,82,64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6630103,SB11202430031940,111001012963,111001012963,3.0,A2,3.0,2.0,3.0,11,11001,BOGOTÁ,BOGOTÁ D.C.,74.0,64.0,87.0,75.0,10.0,84.0,20242,58,276,66.0,61,36,62
6630104,SB11202430002696,320001006881,320001006881,1.0,A-,3.0,2.0,1.0,20,20001,CESAR,VALLEDUPAR,6.0,23.0,37.0,55.0,20.0,27.0,20242,35,215,46.0,55,41,40
6630105,SB11202430070974,176520002520,176520800222,2.0,A1,3.0,2.0,2.0,76,76520,VALLE,PALMIRA,34.0,47.0,66.0,78.0,43.0,34.0,20242,45,251,55.0,62,50,42
6630106,SB11202430586516,305001020558,305001020558,1.0,A-,1.0,1.0,1.0,5,5001,ANTIOQUIA,MEDELLÍN,10.0,3.0,8.0,5.0,5.0,3.0,20242,37,165,35.0,35,31,28
6630107,SB11202430450964,141001001593,141001001593,3.0,A2,3.0,2.0,3.0,41,41001,HUILA,NEIVA,78.0,63.0,83.0,53.0,25.0,77.0,20242,59,274,64.0,55,43,59

#### socioeconomic_info

In [42]:
df_socieconomic_info = df_saber11[["estu_consecutivo",
                                    "cole_cod_dane_establecimiento",
                                    "cole_cod_dane_sede",
                                    "estu_inse_individual",
                                    "estu_nse_individual",
                                    "fami_comecarnepescadohuevo",
                                    "fami_comecerealfrutoslegumbre",
                                    "fami_comelechederivados",
                                    "fami_cuartoshogar",
                                    "fami_educacionmadre",
                                    "fami_educacionpadre",
                                    "fami_estratovivienda",
                                    "fami_numhermanos",
                                    "fami_numlibros",
                                    "fami_personashogar",
                                    "fami_situacioneconomica",
                                    "fami_tieneautomovil",
                                    "fami_tienecomputador",
                                    "fami_tieneconsolavideojuegos",
                                    "fami_tienehornomicroogas",
                                    "fami_tieneinternet",
                                    "fami_tienelavadora",
                                    "fami_tienemotocicleta",
                                    "fami_tieneserviciotv",
                                    "fami_trabajolabormadre",
                                    "fami_trabajolaborpadre"]]

In [43]:
df_socieconomic_info = df_socieconomic_info.rename(columns={"estu_consecutivo":"student_id",
                                                "cole_cod_dane_establecimiento":"school_institution_id",
                                                "cole_cod_dane_sede":"school_campus_id"})

In [44]:
df_socieconomic_info

,student_id,school_institution_id,school_campus_id,estu_inse_individual,estu_nse_individual,fami_comecarnepescadohuevo,fami_comecerealfrutoslegumbre,fami_comelechederivados,fami_cuartoshogar,fami_educacionmadre,fami_educacionpadre,fami_estratovivienda,fami_numhermanos,fami_numlibros,fami_personashogar,fami_situacioneconomica,fami_tieneautomovil,fami_tienecomputador,fami_tieneconsolavideojuegos,fami_tienehornomicroogas,fami_tieneinternet,fami_tienelavadora,fami_tienemotocicleta,fami_tieneserviciotv,fami_trabajolabormadre,fami_trabajolaborpadre
0,SB11201510000485,311769000921,311769000921,74.361115,NSE4,NaN,NaN,NaN,Tres,Educación profesional completa,Educación profesional completa,Estrato 6,NaN,MÁS DE 100 LIBROS,Cuatro,NaN,Si,Si,NaN,NaN,Si,Si,NaN,Si,NaN,NaN
1,SB11201510115564,376250000871,376250000871,44.367836,NSE2,NaN,NaN,NaN,Tres,Secundaria (Bachillerato) incompleta,Secundaria (Bachillerato) completa,Estrato 1,NaN,0 A 10 LIBROS,Cinco,NaN,No,No,NaN,NaN,No,No,NaN,No,NaN,NaN
2,SB11201510097089,311001105928,311001105928,52.914814,NSE3,NaN,NaN,NaN,Siete,Primaria completa,Secundaria (Bachillerato) incompleta,Estrato 2,NaN,0 A 10 LIBROS,Once,NaN,No,Si,NaN,NaN,Si,Si,NaN,Si,NaN,NaN
3,SB11201510115560,376250000871,376250000871,43.844238,NSE2,NaN,NaN,NaN,Dos,Primaria completa,Primaria incompleta,Estrato 1,NaN,11 A 25 LIBROS,Tres,NaN,No,No,NaN,NaN,No,Si,NaN,Si,NaN,NaN
4,SB11201510002784,308001004209,308001004209,86.204170,NSE4,NaN,NaN,NaN,Cuatro,Postgrado,Postgrado,Estrato 6,NaN,26 A 100 LIBROS,Cuatro,NaN,Si,Si,NaN,NaN,Si,Si,NaN,Si,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6630103,SB11202430031940,111001012963,111001012963,47.959408,2.0,1 o 2 veces por semana,3 a 5 veces por semana,Nunca o rara vez comemos eso,Dos,Secundaria (Bachillerato) incompleta,Secundaria (Bachillerato) incompleta,Estrato 3,NaN,11 A 25 LIBROS,1 a 2,Igual,No,No,No,Si,Si,No,No,Si,"Trabaja como personal de limpieza, mantenimien...",Es vendedor o trabaja en atención al público
6630104,SB11202430002696,320001006881,320001006881,58.090347,3.0,3 a 5 veces por semana,1 o 2 veces por semana,Todos o casi todos los días,NaN,No sabe,Técnica o tecnológica completa,Estrato 3,NaN,0 A 10 LIBROS,NaN,NaN,NaN,NaN,NaN,NaN,Si,NaN,NaN,Si,NaN,NaN
6630105,SB11202430070974,176520002520,176520800222,45.675056,2.0,1 o 2 veces por semana,Nunca o rara vez comemos eso,Nunca o rara vez comemos eso,Cuatro,Secundaria (Bachillerato) incompleta,Secundaria (Bachillerato) incompleta,Estrato 2,NaN,0 A 10 LIBROS,3 a 4,Igual,No,No,No,No,Si,Si,Si,Si,Es vendedor o trabaja en atención al público,Es vendedor o trabaja en atención al público
6630106,SB11202430586516,305001020558,305001020558,56.240772,3.0,Todos o casi todos los días,Todos o casi todos los días,Todos o casi todos los días,Tres,Secundaria (Bachillerato) completa,No sabe,Estrato 3,NaN,0 A 10 LIBROS,5 a 6,Mejor,No,Si,Si,No,No,Si,Si,Si,"Trabaja como personal de limpieza, mantenimien...",No aplica
6630107,SB11202430450964,141001001593,141001001593,52.201481,3.0,1 o 2 veces por semana,3 a 5 veces por semana,3 a 5 veces por semana,Tres,Secundaria (Bachillerato) completa,Secundaria (Bachillerato) completa,Estrato 2,NaN,NaN,3 a 4,Igual,Si,Si,No,No,Si,Si,No,Si,"Trabaja en el hogar, no trabaja o estudia","Trabaja como personal de limpieza, mantenimien..."

## Write csv

In [45]:
import json

In [46]:
# Output folder for joined CSV files
joined_path = project_path / "data" / "joined"

# Create folder if it does not exist
joined_path.mkdir(parents=True, exist_ok=True)

In [47]:
dataframes = {
    "student_info": df_student_info,
    "school_info": df_school_info,
    "result_info": df_result_info,
    "socioeconomic_info": df_socieconomic_info,
}

# Dictionary to store the data types of each DataFrame
data_types = {}

for name, df in dataframes.items():

    # Save DataFrame as CSV
    df.to_csv(
        joined_path / f"{name}.csv",
        sep=";",
        index=False,
        encoding="utf-8-sig"
    )

    # Save column data types
    data_types[name] = {
        column: str(dtype)
        for column, dtype in df.dtypes.items()
    }

# Save data types as JSON
with open(
    joined_path / "data_types_student.json",
    "w",
    encoding="utf-8"
) as file:
    json.dump(
        data_types,
        file,
        indent=4,
        ensure_ascii=False
    )