# Teacher information - Translation
    - Author: Santiago Avella. Git hub: https://github.com/TiagoMimi

In [422]:
import pandas as pd
from pathlib import Path
import json
# *Configure pandas to display all columns in DataFrame outputs*
pd.set_option('display.max_columns', None)

# Load Data

In [423]:
# Current working directory
script_path = Path.cwd()

# Find the project folder
project_path = script_path

while project_path.name != "github":
    project_path = project_path.parent

In [424]:
data_path = project_path / "saber11_db" / "data" / "joined" 

# Read teacher data types
with open(
    data_path / "data_types_teacher.json",
    "r",
    encoding="utf-8"
) as file:
    data_type_teacher = json.load(file)


# List of CSV files
file_list = [
    data_path / "teacher_schedule.csv",
    data_path / "teacher_rank.csv",
    data_path / "teacher_employment.csv",
    data_path / "teacher_education.csv",
    data_path / "teacher_clei.csv",
    data_path / "teacher_age.csv",
    data_path / "teacher_academic_assignment.csv"
]


# DataFrame names
df_names = [
    "df_teacher_schedule",
    "df_teacher_rank",
    "df_teacher_employment",
    "df_teacher_education",
    "df_teacher_clei",
    "df_teacher_age",
    "df_teacher_academic_assignment"
]


# Read CSV files using the data types stored in the JSON files
dataframes = {}

for name, file in zip(df_names, file_list):

    # Get table name
    table_name = name.replace("df_", "")

    # Select the corresponding data type dictionary
    if table_name.startswith("teacher_"):
        dtype_mapping = data_type_teacher[table_name]
    else:
        print("ERROR")

    # Read CSV
    dataframes[name] = pd.read_csv(
        file,
        sep=";",
        dtype=dtype_mapping,
        low_memory=False
    )


# Assign DataFrames
df_teacher_schedule = dataframes["df_teacher_schedule"]
df_teacher_rank = dataframes["df_teacher_rank"]
df_teacher_employment = dataframes["df_teacher_employment"]
df_teacher_education = dataframes["df_teacher_education"]
df_teacher_clei = dataframes["df_teacher_clei"]
df_teacher_age = dataframes["df_teacher_age"]
df_teacher_academic_assignment = dataframes["df_teacher_academic_assignment"]

In [425]:
def translate_values_dictionary(df,column,dict_translation):
    
    df[column] = df[column].replace(dict_translation)

    return df

# Teacher Schedule

#### school_campus_id => SCHOOL_CAMPUS_ID

- Id público de la institución educativa 
- Public Identifier of the educational institution

In [426]:
df_teacher_schedule = df_teacher_schedule.rename(columns={"school_campus_id":"SCHOOL_CAMPUS_ID"})

#### PERIODO_ID => DELETE

- Id del periodo de tiempo en que se realizó la encuesta.
- Period of time's ID when the survey was applied

In [427]:
df_teacher_schedule = df_teacher_schedule.drop(columns={"PERIODO_ID"})

#### PERIODO_ANIO => YEAR

- Año en que se realizó la encuesta
- Year when the survey was applied

In [428]:
df_teacher_schedule = df_teacher_schedule.rename(columns={"PERIODO_ANIO":"YEAR"})

#### JORNADA_CODIGO AND JORNADA ID => DELETE

In [429]:
df_teacher_schedule = df_teacher_schedule.drop(columns={"JORNADA_CODIGO","JORNADA_ID"})

#### JORNADA_NOMBRE => TEACHER_SHIFT

- Jornada en la que trabaja el profesor
- Shift whcich the teacher works

In [430]:
df_teacher_schedule = df_teacher_schedule.rename(columns={"JORNADA_NOMBRE":"TEACHER_SHIFT"})

In [431]:
dict_translation = {"Mañana":"morning",
                    "TARDE":"afternoon",
                    "Completa/Única (No oficiales)":"full_day",
                    "Única (Oficiales)":"full_day",
                    "MaÃ±ana":"morning",
                    "Fin de Semana":"weekend",
                    "Nocturna":"night",
                    "Ãnica / Completa":"full_day"}

In [432]:
df_teacher_schedule = translate_values_dictionary(df_teacher_schedule,
                                            "TEACHER_SHIFT",
                                            dict_translation)

#### JORDOC_CANTIDAD_HOMBRE => TEACHERS_MEN

- Número de hombres que trabajan en la jornada
- Total number of mens that works as teacher

In [433]:
df_teacher_schedule = df_teacher_schedule.rename(columns={"JORDOC_CANTIDAD_HOMBRE":"TEACHERS_MEN"})

#### JORDOC_CANTIDAD_MUJER => TEACHERS_WOMEN

- Número de mujeres que trabajan en la jornada
- Total number of women that works as teacher

In [434]:
df_teacher_schedule = df_teacher_schedule.rename(columns={"JORDOC_CANTIDAD_MUJER":"TEACHERS_WOMEN"})

## Write CSV

In [435]:
file_path = Path("../../../saber11_db/data/english//teacher_schedule_EN.csv")
file_path.parent.mkdir(parents=True, exist_ok=True)
df_teacher_schedule.to_csv(file_path, sep=";", index=False)

# Teacher Rank

#### school_campus_id => SCHOOL_CAMPUS_ID

- Id público de la institución educativa 
- Public Identifier of the educational institution

In [436]:
df_teacher_rank = df_teacher_rank.rename(columns={"school_campus_id":"SCHOOL_CAMPUS_ID"})

#### PERIODO_ID => DELETE

- Id del periodo de tiempo en que se realizó la encuesta.
- Period of time's ID when the survey was applied

In [437]:
df_teacher_rank = df_teacher_rank.drop(columns={"PERIODO_ID"})

#### PERIODO_ANIO => YEAR

- Año en que se realizó la encuesta
- Year when the survey was applied

In [438]:
df_teacher_rank = df_teacher_rank.rename(columns={"PERIODO_ANIO":"YEAR"})

#### GRADOESCA_ID	GRADOESCA_CODIGO => DELETE

In [439]:
df_teacher_rank = df_teacher_rank.drop(columns={"GRADOESCA_ID","GRADOESCA_CODIGO"})

#### GRADOESCA_NOMBRE => TEACHER_RANKS_NAME

- Nombre del grado del grado del profesor en el escalafon
- Teacher's rank name in the salary scale

In [440]:
df_teacher_rank = df_teacher_rank.rename(columns={"GRADOESCA_NOMBRE":"TEACHER_RANKS_NAME"})

In [441]:
dict_translation = {
    "Grado 14": "rank_14",
    "Grado 2A Sin especialización": "rank_2a_without_specialization",
    "Grado 1A": "rank_1a",
    "Grado 2A Con especialización": "rank_2a_with_specialization",
    "Grado 13": "rank_13",
    "Grado 2B Con especialización": "rank_2b_with_specialization",
    "Grado 7": "rank_7",
    "Grado 2B Sin especialización": "rank_2b_without_specialization",
    "Grado 3A Maestría": "rank_3a_master's_degree",
    "Grado 12": "rank_12",
    "Grado 8": "rank_8",
    "Grado 3B Maestría": "rank_3b_master's_degree",
    "Grado 2C Con especialización": "rank_2c_with_specialization",
    "Grado 10": "rank_10",
    "Grado 4": "rank_4",
    "Grado 3C Maestría": "rank_3c_master's_degree",
    "Grado 2C Sin especialización": "rank_2c_without_specialization",
    "Grado 1B": "rank_1b",
    "Grado 2A Sin especializaciÃ³n": "rank_2a_without_specialization",
    "Grado 11": "rank_11",
    "Grado 2B Maestría": "rank_2b_master's_degree",
    "Grado 2A Maestría": "rank_2a_master's_degree",
    "Grado 1": "rank_1",
    "Grado 3D Maestría": "rank_3d_master's_degree",
    "Grado 9": "rank_9",
    "Grado 6": "rank_6",
    "Grado 2D Con especialización": "rank_2d_with_specialization",
    "Grado 2A Con especializaciÃ³n": "rank_2a_with_specialization",
    "Grado 2C Maestría": "rank_2c_master's_degree",
    "Grado 2B Con especializaciÃ³n": "rank_2b_with_specialization",
    "Grado 2": "rank_2",
    "Grado 2D Sin especialización": "rank_2d_without_specialization",
    "Grado 2B Sin especializaciÃ³n": "rank_2b_without_specialization",
    "Grado 1C": "rank_1c",
    "Grado A": "rank_a",
    "Grado 5": "rank_5",
    "Grado 2D Maestría": "rank_2d_master's_degree",
    "Grado 3A MaestrÃ­a": "rank_3a_master's_degree",
    "Grado 3A Doctorado": "rank_3a_doctoral_degree",
    "Licenciado o profesional no licenciado": "licensed_or_non_licensed_professional",
    "Grado 1D": "rank_1d",
    "Grado 2C Con especializaciÃ³n": "rank_2c_with_specialization",
    "Grado 3": "rank_3",
    "Grado 3D Doctorado": "rank_3d_doctoral_degree",
    "Bachiller u otro tipo de formación": "high_school_diploma_or_other_education",
    "Grado 3B Doctorado": "rank_3b_doctoral_degree",
    "Grado 2C Sin especializaciÃ³n": "rank_2c_without_specialization",
    "Grado 3C Doctorado": "rank_3c_doctoral_degree",
    "Grado B": "rank_b",
    "Normalista superior o tecnólogo en educación": "higher_education_normalist_or_education_technologist",
    "Grado 3B MaestrÃ­a": "rank_3b_master's_degree",
    "Licenciado o profesional no licenciado con especialización": "licensed_or_non_licensed_professional_with_specialization",
    "Grado 2D Con especializaciÃ³n": "rank_2d_with_specialization",
    "Grado 3C MaestrÃ­a": "rank_3c_master's_degree",
    "Licenciado o profesional no licenciado con maestria": "licensed_or_non_licensed_professional_with_master's_degree",
    "Grado 3D MaestrÃ­a": "rank_3d_master's_degree",
    "Grado 2D Sin especializaciÃ³n": "rank_2d_without_specialization",
    "Grado 2B Doctorado": "rank_2b_doctoral_degree",
    "Grado 2A Doctorado": "rank_2a_doctoral_degree",
    "Grado 2D Doctorado": "rank_2d_doctoral_degree",
    "Grado 2C Doctorado": "rank_2c_doctoral_degree",
    "Licenciado o profesional no licenciado con doctorado": "licensed_or_non_licensed_professional_with_doctoral_degree",
}

In [442]:
df_teacher_rank = translate_values_dictionary(df_teacher_rank,
                                            "TEACHER_RANKS_NAME",
                                            dict_translation)

#### SEDEDOES_CANTIDAD_HOMBRE => TEACHER_CAMPUS_MEN

- Número de hombres que trabajan en la sede
- Total number of mens on campus

In [443]:
df_teacher_rank = df_teacher_rank.rename(columns={"SEDEDOES_CANTIDAD_HOMBRE":"TEACHER_CAMPUS_MEN"})

#### SEDEDOES_CANTIDAD_MUJER => TEACHER_CAMPUS_WOMAN

- Número de mujeres que trabajan en la sede
- Total number of woman on campus

In [444]:
df_teacher_rank = df_teacher_rank.rename(columns={"SEDEDOES_CANTIDAD_MUJER":"TEACHER_CAMPUS_WOMAN"})

## Write CSV

In [445]:
file_path = Path("../../../saber11_db/data/english//teacher_rank_EN.csv")
file_path.parent.mkdir(parents=True, exist_ok=True)
df_teacher_rank.to_csv(file_path, sep=";", index=False)

# TEACHAER EMPLOYMENT

#### school_campus_id => SCHOOL_CAMPUS_ID

- Id público de la institución educativa 
- Public Identifier of the educational institution

In [446]:
df_teacher_rank = df_teacher_rank.rename(columns={"school_campus_id":"SCHOOL_CAMPUS_ID"})

#### PERIODO_ID => DELETE

- Id del periodo de tiempo en que se realizó la encuesta.
- Period of time's ID when the survey was applied

In [447]:
df_teacher_employment = df_teacher_employment.drop(columns={"PERIODO_ID"})

#### PERIODO_ANIO => YEAR

- Año en que se realizó la encuesta
- Year when the survey was applied

In [448]:
df_teacher_rank = df_teacher_rank.rename(columns={"PERIODO_ANIO":"YEAR"})

#### VINCULA_CODIGO	 => DELETE

In [449]:
df_teacher_employment  = df_teacher_employment.drop(columns={"VINCULA_CODIGO"})

#### VINCULA_NOMBRE => TEACHER_EMPLOYMENT_RELATIONSHIP

- Nombre del tipo de vinculación laboral
- Employment Relationship Type Name

In [450]:
df_teacher_employment = df_teacher_employment.rename(columns={"VINCULA_NOMBRE":"TEACHER_EMPLOYMENT_RELATIONSHIP"})

In [451]:
dict_translation = {
    "Docentes de planta, con grado en el escalafón": "permanent_teachers_with_rank",
    "Docentes por contrato, con grado en el escalafón": "contract_teachers_with_rank",
    "Docentes por contrato, sin grado en el escalafón": "contract_teachers_without_rank",
    "Docentes de planta, con grado en el escalafÃ³n": "permanent_teachers_with_rank",
    "Docentes de planta, sin grado en el escalafón": "permanent_teachers_without_rank",
    "Docentes contrato fijo (sin grado en el escalafón)": "fixed_term_contract_teachers_without_rank",
    "Docentes contrato o canasta educativa (con grado en el escalafón)": "contract_or_education_basket_teachers_with_rank",
    "Docentes contrato fijo (con grado en el escalafón)": "fixed_term_contract_teachers_with_rank",
    "Docentes por contrato, con grado en el escalafÃ³n": "contract_teachers_with_rank",
    "Docentes por contrato, sin grado en el escalafÃ³n": "contract_teachers_without_rank",
    "Docentes contrato o canasta educativa (sin grado en el escalafón)": "contract_or_education_basket_teachers_without_rank",
    "Docentes contrato indefinido (sin grado en el escalafón)": "permanent_contract_teachers_without_rank",
    "Docentes contrato indefinido (con grado en el escalafón)": "permanent_contract_teachers_with_rank",
    "Docentes de planta, sin grado en el escalafÃ³n": "permanent_teachers_without_rank"
}

In [452]:
df_teacher_employment = translate_values_dictionary(df_teacher_employment,
                                            "TEACHER_EMPLOYMENT_RELATIONSHIP",
                                            dict_translation)

#### VINCULA_ID	 => ID_TEACHER_EMPLOYMENT_RELATIONSHIP

- ID del tipo de vinculación laboral
- ID of employment Relationship Type Name

In [453]:
df_teacher_employment = df_teacher_employment.rename(columns={"VINCULA_ID":"ID_TEACHER_EMPLOYMENT_RELATIONSHIP"})

#### SEDEDOC_CANTIDAD_HOMBRE => TEACHER_CAMPUS_MEN

- Número de hombres que trabajan en la sede
- Total number of mens on campus

In [454]:
df_teacher_employment = df_teacher_employment.rename(columns={"SEDEDOC_CANTIDAD_HOMBRE":"TEACHER_CAMPUS_MEN"})

#### SEDEDOC_CANTIDAD_MUJER => TEACHER_CAMPUS_WOMAN

- Número de mujeres que trabajan en la sede
- Total number of woman on campus

In [455]:
df_teacher_employment = df_teacher_employment.rename(columns={"SEDEDOC_CANTIDAD_MUJER":"TEACHER_CAMPUS_WOMAN"})

In [456]:
df_teacher_employment

,school_campus_id,PERIODO_ANIO,ID_TEACHER_EMPLOYMENT_RELATIONSHIP,TEACHER_EMPLOYMENT_RELATIONSHIP,TEACHER_CAMPUS_MEN,TEACHER_CAMPUS_WOMAN
0,285001001340,2015,1,permanent_teachers_with_rank,7,7
1,285001001340,2015,2,contract_teachers_with_rank,0,2
2,250223000203,2015,1,permanent_teachers_with_rank,1,1
3,268101000781,2015,1,permanent_teachers_with_rank,5,4
4,268101000781,2015,2,contract_teachers_with_rank,1,1
...,...,...,...,...,...,...
629993,244560000975,2024,3,permanent_teachers_without_rank,11,28
629994,244560000975,2024,1,permanent_teachers_with_rank,0,1
629995,413140000259,2024,1,permanent_teachers_with_rank,4,2
629996,413140000259,2024,2,contract_or_education_basket_teachers_with_rank,3,2
629997,254001003196,2024,1,permanent_teachers_with_rank,15,18

## Write CSV

In [457]:
file_path = Path("../../../saber11_db/data/english//teacher_employment_EN.csv")
file_path.parent.mkdir(parents=True, exist_ok=True)
df_teacher_employment.to_csv(file_path, sep=";", index=False)

# Teacher Education

#### school_campus_id => SCHOOL_CAMPUS_ID

- Id público de la institución educativa 
- Public Identifier of the educational institution

In [458]:
df_teacher_education = df_teacher_education.rename(columns={"school_campus_id":"SCHOOL_CAMPUS_ID"})

#### PERIODO_ID => DELETE

- Id del periodo de tiempo en que se realizó la encuesta.
- Period of time's ID when the survey was applied

In [459]:
df_teacher_education = df_teacher_education.drop(columns={"PERIODO_ID"})

#### PERIODO_ANIO => YEAR

- Año en que se realizó la encuesta
- Year when the survey was applied

In [460]:
df_teacher_education = df_teacher_education.rename(columns={"PERIODO_ANIO":"YEAR"})

#### NIVELEDUCDOC_ID and NIVELEDUCDOC_CODIGO => DELETE

In [461]:
df_teacher_education = df_teacher_education.drop(columns={"NIVELEDUCDOC_ID","NIVELEDUCDOC_CODIGO"})

#### NIVELEDUCDOC_ID and NIVELEDUCDOC_CODIGO => DELETE

- Nivel máximo educativo alcanzado por el profesor.
- Teacher's highest educational attainment

In [462]:
df_teacher_education = df_teacher_education.rename(columns={"NIVELEDUCDOC_NOMBRE":"TEACHER_EDUCATION"})

## Write CSV

In [463]:
file_path = Path("../../../saber11_db/data/english//teacher_education_EN.csv")
file_path.parent.mkdir(parents=True, exist_ok=True)
df_teacher_education.to_csv(file_path, sep=";", index=False)

# Teacher Clei

#### school_campus_id => SCHOOL_CAMPUS_ID

- Id público de la institución educativa 
- Public Identifier of the educational institution

In [464]:
df_teacher_clei = df_teacher_clei.rename(columns={"school_campus_id":"SCHOOL_CAMPUS_ID"})

#### PERIODO_ID => DELETE

- Id del periodo de tiempo en que se realizó la encuesta.
- Period of time's ID when the survey was applied

In [465]:
df_teacher_clei = df_teacher_clei.drop(columns={"PERIODO_ID"})

#### PERIODO_ANIO => YEAR

- Año en que se realizó la encuesta
- Year when the survey was applied

In [466]:
df_teacher_clei = df_teacher_clei.rename(columns={"PERIODO_ANIO":"YEAR"})

#### NIVELENSE_ID and  NIVELENSE_CODIGO	=> DELETE

In [467]:
df_teacher_clei = df_teacher_clei.drop(columns={"NIVELENSE_ID","NIVELENSE_CODIGO"})

#### NIVELENSE_NOMBRE => LEVEL_EDUCATION_NAME

In [468]:
df_teacher_clei = df_teacher_clei.rename(columns={"NIVELENSE_NOMBRE":"LEVEL_EDUCATION_NAME"})

In [469]:
dict_translation = {
    "CLEI (Ciclos lectivos integrados - decreto 3011 de 1997)": "clei",
    "Otros modelos educativos para jóvenes y adultos": "other_educational_models_youth_adults",
}

In [470]:
df_teacher_clei = translate_values_dictionary(df_teacher_clei,
                                            "LEVEL_EDUCATION_NAME",
                                            dict_translation)

#### SEDEDONI_CANTIDAD_HOMBRE => TEACHER_CAMPUS_MEN

- Número de hombres que trabajan en la sede
- Total number of mens on campus

In [471]:
df_teacher_clei = df_teacher_clei.rename(columns={"SEDEDONI_CANTIDAD_HOMBRE":"TEACHER_CAMPUS_MEN"})

#### SEDEDONI_CANTIDAD_MUJER => TEACHER_CAMPUS_WOMAN

- Número de mujeres que trabajan en la sede
- Total number of woman on campus

In [472]:
df_teacher_clei = df_teacher_clei.rename(columns={"SEDEDONI_CANTIDAD_MUJER":"TEACHER_CAMPUS_WOMAN"})

## Write CSV

In [473]:
file_path = Path("../../../saber11_db/data/english//teacher_clei_EN.csv")
file_path.parent.mkdir(parents=True, exist_ok=True)
df_teacher_clei.to_csv(file_path, sep=";", index=False)

# Teacher Age

#### school_campus_id => SCHOOL_CAMPUS_ID

- Id público de la institución educativa 
- Public Identifier of the educational institution

In [474]:
df_teacher_age = df_teacher_age.rename(columns={"school_campus_id":"SCHOOL_CAMPUS_ID"})

#### PERIODO_ID => DELETE

- Id del periodo de tiempo en que se realizó la encuesta.
- Period of time's ID when the survey was applied

In [475]:
df_teacher_age = df_teacher_age.drop(columns={"PERIODO_ID"})

#### PERIODO_ANIO => YEAR

- Año en que se realizó la encuesta
- Year when the survey was applied

In [476]:
df_teacher_age = df_teacher_age.rename(columns={"PERIODO_ANIO":"YEAR"})

#### 	RANGODOCENTE_ID => DELETE

In [477]:
df_teacher_age = df_teacher_age.drop(columns={"RANGODOCENTE_ID"})

#### RANDOC_NOMBRE => TEACHER_RANGE_AGE

- Rango etario del profesor
- Teacher's age range

In [478]:
df_teacher_age = df_teacher_age.rename(columns={"RANDOC_NOMBRE":"TEACHER_RANGE_AGE"})

In [479]:
dict_translation = {
    "Mayor a 40 años": "40+",
    "Entre 36 y 40 años": "36_40",
    "Entre 31 y 35 años": "31_35",
    "Entre 26 y 30 años": "26_30",
    "Entre 41 y 45 aÃ±os": "41_45",
    "Mayor a 56 aÃ±os": "56+",
    "Entre 46 y 50 aÃ±os": "46_50",
    "Entre 51 y 55 aÃ±os": "51_55",
    "Mayor a 40 aÃ±os": "40+",
    "Entre 20 y 25 años": "20_25",
    "Entre 36 y 40 aÃ±os": "36_40",
    "Entre 31 y 35 aÃ±os": "31_35",
    "Menor de 25 años": "less_25",
    "Menor de 25 aÃ±os": "less_25",
    "Entre 26 y 30 aÃ±os": "26_30",
    "Entre 20 y 25 aÃ±os": "20_25",
    "Menor a 20 años": "less_20",
    "Menor a 20 aÃ±os": "less_20"
}

In [480]:
df_teacher_age = translate_values_dictionary(df_teacher_age,
                                            "TEACHER_RANGE_AGE",
                                            dict_translation)

## Write CSV

In [481]:
file_path = Path("../../../saber11_db/data/english//teacher_age_EN.csv")
file_path.parent.mkdir(parents=True, exist_ok=True)
df_teacher_age.to_csv(file_path, sep=";", index=False)

In [482]:
df_teacher_age

        SCHOOL_CAMPUS_ID  YEAR TEACHER_RANGE_AGE
0           205483000236  2016             26_30
1           205483000236  2016             36_40
2           205483000236  2016               40+
3           205483000236  2016             36_40
4           205483000236  2016             36_40
...                  ...   ...               ...
2040111     205120001095  2024               56+
2040112     205120001095  2024             51_55
2040113     205120001095  2024             46_50
2040114     205120001095  2024               56+
2040115     205120001095  2024               56+

[2040116 rows x 3 columns]

# Teacher Academic Assigment

#### school_campus_id => SCHOOL_CAMPUS_ID

- Id público de la institución educativa 
- Public Identifier of the educational institution

In [483]:
df_teacher_academic_assignment = df_teacher_academic_assignment.rename(columns={"school_campus_id":"SCHOOL_CAMPUS_ID"})

#### PERIODO_ID => DELETE

- Id del periodo de tiempo en que se realizó la encuesta.
- Period of time's ID when the survey was applied

In [484]:
df_teacher_academic_assignment = df_teacher_academic_assignment.drop(columns={"PERIODO_ID"})

#### PERIODO_ANIO => YEAR

- Año en que se realizó la encuesta
- Year when the survey was applied

In [485]:
df_teacher_academic_assignment = df_teacher_academic_assignment.rename(columns={"PERIODO_ANIO":"YEAR"})

#### 	CARACTER_ID	CARACTER_CODIGO => DELETE

In [486]:
df_teacher_academic_assignment = df_teacher_academic_assignment.drop(columns={"CARACTER_ID","CARACTER_CODIGO"})

#### CARACTER_NOMBRE => TEACHER_TYPE_EDUCATION

- Nombre del tipo de educación que imparte el profesor
- Name of the type of education taught by the teacher

In [487]:
df_teacher_academic_assignment = df_teacher_academic_assignment.rename(columns={"CARACTER_NOMBRE":"TEACHER_TYPE_EDUCATION"})

In [488]:
dict_translation = {
    "Académico": "academic",
    "AcadÃ©mico": "academic",
    "Técnico": "technical",
    "TÃ©cnico": "technical",
    "Normalista": "teacher_training"
}

In [489]:
df_teacher_academic_assignment = translate_values_dictionary(df_teacher_academic_assignment,
                                            "TEACHER_TYPE_EDUCATION",
                                            dict_translation)

#### NIVELENSE_NOMBRE => TEACHER_GRADE

- Grados en donde enseña el profesor
- Grades in which the teacher teaches

In [490]:
df_teacher_academic_assignment = df_teacher_academic_assignment.rename(columns={"NIVELENSE_NOMBRE":"TEACHER_GRADE"})

In [491]:
dict_translation = {
    "Básica primaria": "basic_elementary",
    "Básica secundaria": "basic_secundary",
    "Media": "highschool",
    "BÃ¡sica primaria": "basic_elementary",
    "Preescolar": "kinder_garden",
    "BÃ¡sica secundaria":"basic_secundary"
}

In [492]:
df_teacher_academic_assignment = translate_values_dictionary(df_teacher_academic_assignment,
                                            "TEACHER_GRADE",
                                            dict_translation)

#### NIVELENSE_ID AND NIVELENSE_CODIGO => DELETE

In [493]:
df_teacher_academic_assignment = df_teacher_academic_assignment.drop(columns={"NIVELENSE_ID","NIVELENSE_CODIGO"})

#### ESPECIALIDAD_NOMBRE => TEACHER_SPECIALIZATION_SUBJECT

- ¿Donde tienen la mayor asignación académica el profesor?
- Where does the teacher have the highest teaching workload?

In [494]:
df_teacher_academic_assignment = df_teacher_academic_assignment.rename(columns={"ESPECIALIDAD_NOMBRE":"TEACHER_SPECIALIZATION_SUBJECT"})

In [495]:
dict_translation = {
    "Todas las áreas": "all_areas",
    "Humanidades, lengua castellana": "humanities_and_spanish_language",
    "Matemáticas": "mathematics",
    "Ciencias naturales y educación ambiental": "natural_sciences_and_environmental_education",
    "Dimensiones": "developmental_dimensions",
    "Idiomas extranjeros": "foreign_languages",
    "Educación física, recreación y deportes": "physical_education_recreation_and_sports",
    "Tecnología e informática": "technology_and_computing",
    "Educación artística y cultural": "arts_and_cultural_education",
    "Ciencias sociales, historia, geografía, constitución política, etc.": "social_sciences_history_geography_political_constitution_etc",
    "Educación ética y en valores humanos": "ethics_and_human_values_education",
    "Ciencias sociales, historia, geografía, constitución política y democracia": "social_sciences_history_geography_political_constitution_etc",
    "Educación religiosa": "religious_education",
    "Todas las Ã¡reas": "all_areas",
    "MatemÃ¡ticas": "mathematics",
    "Ciencias naturales y educaciÃ³n ambiental": "natural_sciences_and_environmental_education",
    "Ciencias sociales, historia, geograf¿¿a, constituci¿¿n pol¿¿tica y democracia": "social_sciences_history_geography_political_constitution_etc",
    "Ciencias sociales, historia, geografÃ­a, constituciÃ³n polÃ­tica, etc.": "social_sciences_history_geography_political_constitution_etc",
    "Humanidades, lengua castellana e idiomas extranjeros": "humanities_spanish_language_and_foreign_languages",
    "Filosofía": "philosophy",
    "EducaciÃ³n fÃ­sica, recreaciÃ³n y deportes": "physical_education_recreation_and_sports",
    "TecnologÃ­a e informÃ¡tica": "technology_and_computing",
    "Comercial": "commercial_education",
    "Agropecuario": "agricultural_education",
    "EducaciÃ³n artÃ­stica y cultural": "arts_and_cultural_education",
    "EducaciÃ³n Ã©tica y en valores humanos": "ethics_and_human_values_education",
    "EducaciÃ³n religiosa": "religious_education",
    "Ciencias políticas": "political_science",
    "Industrial": "industrial_education",
    "Ciencias Económicas": "economics",
    "Otros": "other",
    "Normalista": "teacher_training",
    "Técnico social": "social_technical_education"
}

In [496]:
df_teacher_academic_assignment = translate_values_dictionary(df_teacher_academic_assignment,
                                            "TEACHER_SPECIALIZATION_SUBJECT",
                                            dict_translation)

#### ESPECIALIDAD_ID AND ESPECIALIDAD_CODIGO => DELETE

In [497]:
df_teacher_academic_assignment = df_teacher_academic_assignment.drop(columns={"ESPECIALIDAD_ID","ESPECIALIDAD_CODIGO"})

#### SEDEDOCA_CANTIDAD_HOMBRE => TEACHER_CAMPUS_MEN

- Número de hombres que trabajan en la sede
- Total number of mens on campus

In [498]:
df_teacher_academic_assignment = df_teacher_academic_assignment.rename(columns={"SEDEDOCA_CANTIDAD_HOMBRE":"TEACHER_CAMPUS_MEN"})

#### SEDEDOCA_CANTIDAD_MUJER => TEACHER_CAMPUS_WOMAN

- Número de mujeres que trabajan en la sede
- Total number of woman on campus

In [499]:
df_teacher_academic_assignment = df_teacher_academic_assignment.rename(columns={"SEDEDOCA_CANTIDAD_MUJER":"TEACHER_CAMPUS_WOMAN"})

## Write CSV

In [500]:
file_path = Path("../../../saber11_db/data/english//teacher_assignment_EN.csv")
file_path.parent.mkdir(parents=True, exist_ok=True)
df_teacher_academic_assignment.to_csv(file_path, sep=";", index=False)

In [263]:
df_teacher_academic_assignment

,SCHOOL_CAMPUS_ID,YEAR,TEACHER_TYPE_EDUCATION,TEACHER_GRADE,TEACHER_SPECIALIZATION_SUBJECT,TEACHER_CAMPUS_MEN,TEACHER_CAMPUS_WOMAN
0,250287000223,2015,academic,basic_elementary,all_areas,0,1
1,244001002747,2015,academic,kinder_garden,all_areas,0,1
2,244001002747,2015,academic,basic_elementary,all_areas,0,1
3,244560003362,2015,academic,kinder_garden,all_areas,1,3
4,244560003362,2015,academic,basic_elementary,all_areas,6,12
...,...,...,...,...,...,...,...
2313567,368547001998,2024,academic,basic_elementary,natural_sciences_and_environmental_education,1,1
2313568,368547001998,2024,academic,basic_elementary,social_sciences_history_geography_political_co...,0,1
2313569,368547001998,2024,academic,basic_elementary,humanities_and_spanish_language,0,2
2313570,368547001998,2024,academic,basic_elementary,mathematics,0,2
2313571,368547001998,2024,academic,kinder_garden,developmental_dimensions,0,3